"""empty message

Revision ID: f19c948f949d
Revises: e1da4b4e9ecb
Create Date: 2021-03-07 14:45:11.984663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19c948f949d'
down_revision = 'e1da4b4e9ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('Age', sa.String(length=30), nullable=False),
    sa.Column('Gender', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('mobno', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=25), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.drop_table('contact')
    # ### end Alembic commands ###
